site_name: Zoofs

repo_url: https://github.com/jaswinder9051998/zoofs/

nav:
  - Introduction: 'index.md'
  - Examples:
    - Particle Swarm : Particle_swarm_optimization_example.ipynb
    - Grey Wolf : Grey_wolf_optimization_example.ipynb
    - Dragon Fly: Dragon_Fly_optimization_example.ipynb
    - Genetic algo : Genetic_optimization_example.ipynb



theme:
  name: material

plugins:
  - mkdocstrings
  - mkdocs-jupyter
