site_name: Zoofs
banner_url: https://ik.imagekit.io/mwxq2z9h7suv/zoofsedited_-eTl4mZwg.png?updatedAt=1631185077950
logo: https://ik.imagekit.io/mwxq2z9h7suv/zoofsedited_-eTl4mZwg.png?updatedAt=1631185077950
banner_url: https://ik.imagekit.io/mwxq2z9h7suv/zoofsedited_-eTl4mZwg.png?updatedAt=1631185077950

repo_url: https://github.com/jaswinder9051998/zoofs/

nav:
  - Introduction: 'index.md'


theme:
  name: material

plugins:
  - mkdocstrings
