name: MkDocs 
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install pandas
      - run: pip install numpy
      - run: pip install scipy
      - run: pip install plotly
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings
      - run: pip install mkdocstrings
      - run: pip install pytkdocs 
      - run: pip install mkdocs-jupyter
      - run: pip install mkdocs-meta-descriptions-plugin
      - run: pip install jupyter_contrib_nbextensions
      - run: mkdocs gh-deploy --force

